
## audit: all - tidy, lints, tests
.PHONY: audit
audit:
	@echo Checking module dependencies...
	go mod tidy -diff
	go mod verify
	@echo Linting...
	golangci-lint run ./...
	@echo Running tests...
	go test ./...
